### ISSUE TITLE
Can this system output 720P and 1080P HD video?

### ISSUE THREAD

**Issue by jedisun76cn** [OpenTalker/video-retalking#105]
i found that the system only output low-resolution videos.  could any friend tell me if the system could create HD videos thru special parameter in command line?  
  Thanks !

**Comment by adner1986** [comment]
> i found that the system only output low-resolution videos. could any friend tell me if the system could create HD videos thru special parameter in command line? Thanks !

Has the problem been solved? How was it solved?

**Comment by AIhasArrived** [comment]
Same question @jedisun76cn  @adner1986  @johndpope??

**Comment by Oyiyi** [comment]
What's the default resolution of this model?
