### ISSUE TITLE
Building Wheels for dlib

### ISSUE THREAD

**Issue by KartavyaBagga** [OpenTalker/video-retalking#110]
![image](https://github.com/OpenTalker/video-retalking/assets/66277203/71ab9ef1-a392-490b-a945-abc2c5b100e7)

Installations:
![image](https://github.com/OpenTalker/video-retalking/assets/66277203/03c44923-0477-4b6b-9de8-e6a25619d9fa)

What to do ?

Specs:
RTX 4090, CUDA version 12.2

**Comment by AlexKashi** [comment]
any update?

**Comment by troycjj** [comment]
pip install cmake
