### ISSUE TITLE
Error encountered during video retalking inference

### ISSUE THREAD

**Issue by BryanHarrisScripts** [OpenTalker/video-retalking#123]
Subject: Error encountered during video retalking inference

Description:
While running the video retalking inference script (inference.py), I encountered an error related to the trans_params variable in the align_img function of the third_part/face3d/util/preprocess.py module.

Steps to reproduce:

Navigate to the video-retalking directory.
Run the following command:
css
Copy code
python inference.py --face examples/face/1.mp4 --audio examples/audio/1.wav --outfile results/1_1.mp4
The script starts the inference process and encounters the error during the 3DMM extraction step.
Expected outcome:
The script should successfully process the video and produce the desired output video.

Actual outcome:
The script stops execution with the following error message:

sql
Copy code
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.
The error traces back to the line trans_params = np.array([w0, h0, s, t[0], t[1]]) in the align_img function.

Additional notes:

I'm using Python version 3.11.
I've ensured that all dependencies are installed and up to date.
It would be great if you could look into this issue and provide guidance or a fix. Let me know if you need any more information or files to debug this.

**Comment by tom20180101** [comment]
try this https://github.com/OpenTalker/video-retalking/issues/35#issuecomment-1542944601
