### ISSUE TITLE
torch_extensions/py38_cu113/fused/fused.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cousin-wang** [OpenTalker/video-retalking#129]
ibrary version:

python 3.8.12
torch                     2.1.0+cu118
torchaudio                2.1.0+cu118
torchvision               0.16.0+cu118
cuda 11.8
ninja 1.10.2

thank you

**Comment by desis123** [comment]
i am having the same issue , did you able to sole it ?

**Comment by cousin-wang** [comment]
> i am having the same issue , did you able to sole it ?

no

**Comment by cousin-wang** [comment]
> i am having the same issue , did you able to sole it ?

no

**Comment by KepaJRodriguez** [comment]
Same problem with:
Python 3.10.12
torch 2.2.1+cu121
torchaudio 2.2.1+cu121
torchvision 0.17.1+cu121
ninja 1.11.1
Did somebody find a solution?

**Comment by maraliycrt** [comment]
I had to run the code in Colab, download the installed libraries and .so files from there, and place them in my local .cache/torch_extensions/py310_cu121/ folders

**Comment by madhurjya-acko** [comment]
@maraliycrt were you able to run it without this hack? Also where did you find the .so from colab ?
