### ISSUE TITLE
This error originates from a subprocess, and is likely not a problem with pip

### ISSUE THREAD

**Issue by EKI-INDRADI** [OpenTalker/video-retalking#132]
---------------------------------------- 185.8/185.8 kB 11.7 MB/s eta 0:00:00
Using cached exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
Building wheels for collected packages: basicsr, face-alignment, dlib, ffmpy, filterpy, future
  Building wheel for basicsr (setup.py) ... done
  Created wheel for basicsr: filename=basicsr-1.4.2-py3-none-any.whl size=214848 sha256=b88b0455bfe15f5c7827d7745d956ea7053d519640d7ce4835037369d1ad8ff1
  Stored in directory: c:\users\ngxcrypt-2nd\appdata\local\pip\cache\wheels\4d\d3\95\e17d0bcdd7dcfb0dbf79db006711e434c42036efbf6695ef7f
  Building wheel for face-alignment (setup.py) ... done
  Created wheel for face-alignment: filename=face_alignment-1.3.4-py2.py3-none-any.whl size=27875 sha256=b63e56428e9ae11b60de5f718762189c5542312d0965e6e388cb793f5d77323e
  Stored in directory: c:\users\ngxcrypt-2nd\appdata\local\pip\cache\wheels\9a\2f\f7\8fcbb38e17b114f00b8975637b6ba7dff376655d9319c516ed
  Building wheel for dlib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext

      ERROR: CMake must be installed to build dlib

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
  Building wheel for ffmpy (setup.py) ... done
  Created wheel for ffmpy: filename=ffmpy-0.3.1-py3-none-any.whl size=5601 sha256=4e2c80986b926454fd97232ee107377b081fb780a584e06b20b033f75916bcf5
  Stored in directory: c:\users\ngxcrypt-2nd\appdata\local\pip\cache\wheels\75\a3\1a\2f3f90b9a4eb0408109ae1b5bae01efbdf8ab4ef98797433e4
  Building wheel for filterpy (setup.py) ... done
  Created wheel for filterpy: filename=filterpy-1.4.5-py3-none-any.whl size=110542 sha256=fe36a233005b76711136ae43c6cf62bd40ed0d4c93c118e559f220297dcd08b5
  Stored in directory: c:\users\ngxcrypt-2nd\appdata\local\pip\cache\wheels\fe\f6\cb\40331472edf4fd399b8cad02973c6acbdf26898342928327fe
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492054 sha256=a4cceb87f86fc3ecb32a9196551d64d1311d5d3faff81a311680b0bec822ef4d
  Stored in directory: c:\users\ngxcrypt-2nd\appdata\local\pip\cache\wheels\a0\0b\ee\e6994fadb42c1354dcccb139b0bf2795271bddfe6253ccdf11
Successfully built basicsr face-alignment ffmpy filterpy future
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

(video_retalking) V:\_video_retalking\video-retalking>

**Comment by potatoker** [comment]
I'm using venv, and `pip install cmake` does not work for me, I resolved it by adding the cmake path in venv bin directory to bashrc PATH

**Comment by EKI-INDRADI** [comment]
> I'm using venv, and `pip install cmake` does not work for me, I resolved it by adding the cmake path in venv bin directory to bashrc PATH

if using windows need install cmake https://cmake.org/download/ 


https://github.com/EKI-INDRADI/video-retalking-tested-20231020

use anaconda

```sh

conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

pip install -r requirements.txt

```

**Comment by wjnodejs** [comment]
> > I'm using venv, and `pip install cmake` does not work for me, I resolved it by adding the cmake path in venv bin directory to bashrc PATH
> 
> if using windows need install cmake https://cmake.org/download/
> 
> https://github.com/EKI-INDRADI/video-retalking-tested-20231020
> 
> use anaconda
> 
> ```shell
> conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
> 
> pip install -r requirements.txt
> ```

when i exc  "conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia" in windows , i getted the message "Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve." , so i want to know what's your conda channels. thanks

**Comment by wjnodejs** [comment]
> > I'm using venv, and `pip install cmake` does not work for me, I resolved it by adding the cmake path in venv bin directory to bashrc PATH
> 
> if using windows need install cmake https://cmake.org/download/
> 
> https://github.com/EKI-INDRADI/video-retalking-tested-20231020
> 
> use anaconda
> 
> ```shell
> conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
> 
> pip install -r requirements.txt
> ```

Still reporting an error，full error message ：

Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [137 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\setup.py:129: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cmake_version) < '3.1.0':
      Building extension for Python 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
      Invoking CMake setup: 'cmake C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\lib.win-amd64-cpython-38 -DPYTHON_EXECUTABLE=D:\install\anaconda3\envs\video-retalking\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\lib.win-amd64-cpython-38 -A x64'
      -- Building for: Visual Studio 16 2019
      CMake Deprecation Warning at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
      -- The C compiler identification is MSVC 19.29.30152.0
      -- The CXX compiler identification is MSVC 19.29.30152.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - broken
      CMake Error at D:/install/anaconda3/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: 'C:/Users/Administrator/AppData/Local/Temp/pip-install-edr1atgw/dlib_cf2c0f4d0ec74ef98a571042490f5553/build/temp.win-amd64-cpython-38/Release/CMakeFiles/CMakeScratch/TryCompile-afgm1u'

          Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_d429c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
          鐢ㄤ簬 .NET Framework 鐨\x84 Microsoft (R) 鐢熸垚寮曟搸鐗堟湰 16.11.2+f32259642
          鐗堟潈鎵\x80鏈\x89(C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿\x80\x82

          鐢熸垚鍚\xaf鍔ㄦ椂闂翠负 2023/11/7 15:48:53銆\x82
          鑺傜偣 1 涓婄殑椤圭洰鈥淐:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj鈥\x9d(榛樿\xaeょ洰鏍\x87)銆\x82
          PrepareForBuild:
            姝ｅ湪鍒涘缓鐩\xae褰曗\x80渃mTC_d429c.dir\Debug\鈥濄\x80\x82
            姝ｅ湪鍒涘缓鐩\xae褰曗\x80淐:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\Debug\鈥濄\x80\x82
            姝ｅ湪鍒涘缓鐩\xae褰曗\x80渃mTC_d429c.dir\Debug\cmTC_d429c.tlog\鈥濄\x80\x82
          InitializeBuildStatus:
            姝ｅ湪鍒涘缓鈥渃mTC_d429c.dir\Debug\cmTC_d429c.tlog\unsuccessfulbuild鈥濓紝鍥犱负宸叉寚瀹氣\x80淎lwaysCreate鈥濄\x80\x82
          ClCompile:
            C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d429c.dir\Debug\\" /Fd"cmTC_d429c.dir\Debug\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\testCCompiler.c"
            鐢ㄤ簬 x64 鐨\x84 Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣\xa8 19.29.30152 鐗\x88
            鐗堟潈鎵\x80鏈\x89(C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿\x80\x82
            testCCompiler.c
            cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d429c.dir\Debug\\" /Fd"cmTC_d429c.dir\Debug\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\testCCompiler.c"
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003: 鎸囧畾鐨勪换鍔″彲鎵ц\xa1屾枃浠垛\x80淐L.exe鈥濇湭鑳借繍琛屻\x80係ystem.IO.DirectoryNotFoundException: 鏈\xaa鑳芥壘鍒拌矾寰勨\x80淐:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.dir\Debug\cmTC_d429c.tlog鈥濈殑涓\x80閮ㄥ垎銆\x82 [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.Utilities.CanonicalTrackedOutputFiles..ctor(ITaskItem[] tlogFiles) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          宸插畬鎴愮敓鎴愰」鐩\xae鈥淐:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj鈥\x9d(榛樿\xaeょ洰鏍\x87)鐨勬搷浣\x9c - 澶辫触銆\x82

          鐢熸垚澶辫触銆\x82

          鈥淐:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj鈥\x9d(榛樿\xaeょ洰鏍\x87) (1) ->
          (ClCompile 鐩\xae鏍\x87) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003: 鎸囧畾鐨勪换鍔″彲鎵ц\xa1屾枃浠垛\x80淐L.exe鈥濇湭鑳借繍琛屻\x80係ystem.IO.DirectoryNotFoundException: 鏈\xaa鑳芥壘鍒拌矾寰勨\x80淐:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.dir\Debug\cmTC_d429c.tlog鈥濈殑涓\x80閮ㄥ垎銆\x82 [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.Utilities.CanonicalTrackedOutputFiles..ctor(ITaskItem[] tlogFiles) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(687,5): error MSB6003:    鍦\xa8 Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\build\temp.win-amd64-cpython-38\Release\CMakeFiles\CMakeScratch\TryCompile-afgm1u\cmTC_d429c.vcxproj]

              0 涓\xaa璀﹀憡
              1 涓\xaa閿欒\xaf\xaf

          宸茬敤鏃堕棿 00:00:00.37





        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:14 (project)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\setup.py", line 222, in <module>
          setup(
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "D:\install\anaconda3\envs\video-retalking\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\setup.py", line 134, in run
          self.build_extension(ext)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-edr1atgw\dlib_cf2c0f4d0ec74ef98a571042490f5553\setup.py", line 171, in build_extension
          subprocess.check_call(cmake_setup, cwd=build_folder)
        File "D:\install\anaconda3\envs\video-retalking\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-edr1atgw\\dlib_cf2c0f4d0ec74ef98a571042490f5553\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-edr1atgw\\dlib_cf2c0f4d0ec74ef98a571042490f5553\\build\\lib.win-amd64-cpython-38', '-DPYTHON_EXECUTABLE=D:\\install\\anaconda3\\envs\\video-retalking\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-edr1atgw\\dlib_cf2c0f4d0ec74ef98a571042490f5553\\build\\lib.win-amd64-cpython-38', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

**Comment by suwei999** [comment]
you must install gcc and g++ like this:
apt-get update
apt-get install build-essential
pip install cmake
pip install -r requirements.txt

it is works for me

**Comment by EKI-INDRADI** [comment]
for windows solved with step : https://github.com/EKI-INDRADI/video-retalking-tested-20231020

**Comment by ismeyueyue** [comment]
try this, install from souce code

git clone https://github.com/davisking/dlib.git
cd dlib
mkdir build; cd build
cmake ..
cmake --build .
cd ..
python setup.py install
