### ISSUE TITLE
About the pre-trained models

### ISSUE THREAD

**Issue by ykhasia** [OpenTalker/video-retalking#148]
In the instruction indicates:"Please download our **pre-trained models** and put them in **./checkpoints**".
Two quesions as below:
1, There are many files in the "pre-trained models" checkpoints direcotory, which model should I download?
![image](https://github.com/OpenTalker/video-retalking/assets/52735731/494a7402-1bb0-46c3-bbfc-a68df050085c)

2, the installed workingspace doesn't has checkpoints directory, should I create a new one ?
![image](https://github.com/OpenTalker/video-retalking/assets/52735731/1166c419-02fd-4978-9c67-1d60ca19e3d5)

**Comment by kunncheng** [comment]
1. All the models.
2. Yes.

**Comment by ykhasia** [comment]
> 1. All the models.
> 2. Yes.

thank you . got it.
