### ISSUE TITLE
Infinite loop at 'from third_part.GPEN.gpen_face_enhancer import FaceEnhancement' line

### ISSUE THREAD

**Issue by AhnJunYeong0319** [OpenTalker/video-retalking#153]
![image](https://github.com/OpenTalker/video-retalking/assets/63603383/305e18b4-8c59-43c5-837a-af3aecebc03f)

As you can see the image above, I suddenly cannot run the inference.py code. To be more precise, I get stuck in ```from third_part.GPEN.gpen_face_enhancer import FaceEnhancement``` line for good.

Anyone knows the reason?

Actually this happened after a few trials of code-running related to .sh file as below.
https://stackoverflow.com/questions/77372134/sh-file-doesnt-run-the-command-running-py-file-with-some-arguments-within-for

Thanks,
Junyeong Ahn

**Comment by kunncheng** [comment]
It is possible that torch extensions are responsible.

You can check `~/.cache/torch_extensions/deform_conv/` or `~/.cache/torch_extensions/fused/` or  `~/.cache/torch_extensions/upfirdn2d/`. 

If there is a lock file, delete it and run the inference script again.

**Comment by AhnJunYeong0319** [comment]
> It is possible that torch extensions are responsible.
> 
> You can check `~/.cache/torch_extensions/deform_conv/` or `~/.cache/torch_extensions/fused/` or `~/.cache/torch_extensions/upfirdn2d/`.
> 
> If there is a lock file, delete it and run the inference script again.

First of all, thank you for your fast response! Actually I don't understand what you mean for now 'exactly', but I'm trying!

One more - I realized that seemingly the prompt is letting me know where the problematic part is.
![image](https://github.com/OpenTalker/video-retalking/assets/63603383/2d475a38-a1cc-450d-b458-7bad1316d1f7)

Do you have any idea about this as well?

Thanks,
Junyeong Ahn

**Comment by kunncheng** [comment]
> > It is possible that torch extensions are responsible.
> > You can check `~/.cache/torch_extensions/deform_conv/` or `~/.cache/torch_extensions/fused/` or `~/.cache/torch_extensions/upfirdn2d/`.
> > If there is a lock file, delete it and run the inference script again.
> 
> First of all, thank you for your fast response! Actually I don't understand what you mean for now 'exactly', but I'm trying!
> 
> One more - I realized that seemingly the prompt is letting me know where the problematic part is. ![image](https://user-images.githubusercontent.com/63603383/278922848-2d475a38-a1cc-450d-b458-7bad1316d1f7.png)
> 
> Do you have any idea about this as well?
> 
> Thanks, Junyeong Ahn

1. Check to see if there is a file named `lock` in each of the three folders
2. Delete `lock` file and try again

**Comment by AhnJunYeong0319** [comment]
> > > It is possible that torch extensions are responsible.
> > > You can check `~/.cache/torch_extensions/deform_conv/` or `~/.cache/torch_extensions/fused/` or `~/.cache/torch_extensions/upfirdn2d/`.
> > > If there is a lock file, delete it and run the inference script again.
> > 
> > 
> > First of all, thank you for your fast response! Actually I don't understand what you mean for now 'exactly', but I'm trying!
> > One more - I realized that seemingly the prompt is letting me know where the problematic part is. ![image](https://user-images.githubusercontent.com/63603383/278922848-2d475a38-a1cc-450d-b458-7bad1316d1f7.png)
> > Do you have any idea about this as well?
> > Thanks, Junyeong Ahn
> 
> 1. Check to see if there is a file named `lock` in each of the three folders
> 2. Delete `lock` file and try again

Thank you so much! It does work. Thank you for providing us such a great project.
Actually I have two more questions left.

1) This happening probably stems from my attempt to run ```.sh``` file such that I can run the similar inference commands multiple times with some varying arguments. Was ```lock``` file created because of that?

2) Three SyntaxWarnings in ```GPEN/align_faces``` occur which have never appeared until 3 days ago, I get the expected output video though. My environment including package dependencies is the same as before. I just wonder why these warnings suddenly occur. Was there any update about this recently?

![image](https://github.com/OpenTalker/video-retalking/assets/63603383/c5681717-298d-4dbb-a35c-098e1eff6b42)



Thank you,
Junyeong Ahn
