### ISSUE TITLE
Evaluating video quality with FID score for evaluating image quality? 

### ISSUE THREAD

**Issue by AhnJunYeong0319** [OpenTalker/video-retalking#156]
Hi forks, I want to evaluate the output video using FID score as the authors did in the paper.
However, as far as I know, FID score is for image. Even though the video consists of the frames(= images), how can I calculate the only one representative FID score for a single video?

Thanks,
Junyeong Ahn

**Comment by justin4ai** [comment]
Sorry for my misunderstand about the calculation! No problem

**Comment by sy77777en** [comment]
Hi! I'm troubled by this problem either! Could you tell me how you solve it?
I'll appreciate it so much!

Yours Sincerely,
Siyuan

**Comment by justin4ai** [comment]
Siyuan, the representative FID score for multiple images is calculated by averaging scores for each frame. Since a video consists of multiple frames, you may apply the same logic to this situation. Or please refer to the specialized Frechet Distance for video cases; FVD.

Best Regards,
Junyeong Ahn
