### ISSUE TITLE
Using cuda for inference. ^C

### ISSUE THREAD

**Issue by tralala87** [OpenTalker/video-retalking#26]
While running google colab, I get:

`/usr/local/lib/python3.9/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[Info] Using cuda for inference.
^C`

**Comment by wwfem** [comment]
try other video and audio
