### ISSUE TITLE
Step2 ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

### ISSUE THREAD

**Issue by yyz845935161** [OpenTalker/video-retalking#34]
![image](https://user-images.githubusercontent.com/51375977/236476117-fa40d74a-6dac-40f4-a80c-802dd32dd789.png)
when I run the command python3 inference.py \
  --face examples/face/1.mp4 \
  --audio examples/audio/1.wav \
  --outfile results/1_1.mp4
  I meet this question.
my device GPU is  3090,cuda is 11.7

**Comment by kunncheng** [comment]
Hi, I have not met this error.
Could you try another video like 2.mp4 or 3.mp4 and see what happens?

**Comment by yyz845935161** [comment]
thanks
I had solved this issue ： pip install numpy==1.2.1 .numpy ==1.24.0 that maybe meet this error

**Comment by GregoryZeng** [comment]
same error after reinstalling the dependency... really weird

**Comment by norris9410** [comment]
As of 2023/05/09:

**Comment by manel-moles** [comment]
> Same error. Mine was 1.24.3, downgrade numpy to version 1.21.1 works for me.

Thanks! It worked for me too.
