### ISSUE TITLE
ValueError: cannot reshape array of size 81600 into shape (742,newaxis,2)

### ISSUE THREAD

**Issue by xuelinghao** [OpenTalker/video-retalking#46]
When I use my own vidoe, it always return this error, would you please help answer? Thank you!

**Comment by kunncheng** [comment]
The inference script will save preprocessing results in `./temp` folder. When the input video has been preprocessed, the preprocessed data are loaded directly from the folder to save inference time.

Did you test two videos with the same name? This can cause the loaded data to be inconsistent with the input video.

You can try deleting `./temp` folder or adding the parameter `--re_preprocess`.

**Comment by xuelinghao** [comment]
Thanks a lot, I got it fixed, no error at all. Really appreciate.

**Comment by BillieFrano** [comment]
thanks a lot Xuelinghao!!!
