### ISSUE TITLE
RuntimeError: unexpected EOF, expected 2644905 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by OceanTan** [OpenTalker/video-retalking#49]
当我使用推理的时候返回`RuntimeError: unexpected EOF, expected 2644905 more bytes. The file might be corrupted.`

**Comment by woshidag** [comment]
请问如何解决，我也遇到同样的问题 （How do I solve the same problem）

**Comment by OceanTan** [comment]
> 请问如何解决，我也遇到同样的问题 （How do I solve the same problem）

模型下载失败了，重新下载

**Comment by gt2ming** [comment]
1、进入当前anaconda环境下的facexlib/weights目录

如：
```
C:\Users\{username}\anaconda3\envs\video_retalking\Lib\site-packages\facexlib\weights
```

2、删掉detection_Resnet50.pth文件
3、重新执行命令
4、如果无法执行，就手动下载pth文件，并放入上面的目录下

下载地址

```
https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth
```
