### ISSUE TITLE
/bin/sh: 1: ffmpeg: not found， step 6后没有任何输出就结束了

### ISSUE THREAD

**Issue by mohican521** [OpenTalker/video-retalking#61]

**Comment by kunncheng** [comment]
Have you installed `ffmpeg`?

**Comment by mohican521** [comment]
Requirement already satisfied: ffmpeg in /root/miniconda3/envs/video_retalking/lib/python3.8/site-packages (1.4)

/bin/sh: 1: ffmpeg: not found
outfile: /root/autodl-tmp/ssc/2_2.mp4

but not found file 2_2.mp4

**Comment by kunncheng** [comment]
Try  `sudo apt install -y ffmpeg`

**Comment by mohican521** [comment]
not work 

(video_retalking) root@autodl-container-f4d5458449-0bcea16b:~/autodl-tmp/ssc# sudo apt install -y ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ffmpeg

**Comment by mohican521** [comment]
user conda solved
