### ISSUE TITLE
inference can't handle my input video, error on step 1

### ISSUE THREAD

**Issue by abrahamU** [OpenTalker/video-retalking#83]
[Info] Using cuda for inference.
[Step 0] Number of frames available for inference: 193
[Step 1] Using saved landmarks.
Traceback (most recent call last):
  File "inference.py", line 345, in <module>
    main()
  File "inference.py", line 86, in main
    lm = lm.reshape([len(full_frames), -1, 2])
ValueError: cannot reshape array of size 18360 into shape (193,newaxis,2)

**Comment by Oyiyi** [comment]
How did you solve it? Thank you!

**Comment by numerized** [comment]
same issue here, what's the catch?
